export const lgaAndStates = {
  "Abia": [
    "Aba North",
    "Aba South",
    "Arochukwu",
    "Bende",
    "Ikwuano",
    "Isiala Ngwa North",
    "Isiala Ngwa South",
    "Isuikwuato",
    "Obingwa",
    "Ohafia",
    "Osisioma",
    "Ugwunagbo",
    "Ukwa East",
    "Ukwa West",
    "Umuahia North",
    "Umuahia South"
  ],
  "Adamawa": [
    "Demsa",
    "Fufore",
    "Ganye",
    "Girei",
    "Gombi",
    "Hong",
    "Jada",
    "Lamurde",
    "Mubi North",
    "Mubi South",
    "Numan",
    "Shelleng",
    "Song",
    "Toungo",
    "Yola North",
    "Yola South"
  ],
  "Akwa Ibom": [
    "Abak",
    "Eastern Obolo",
    "Eket",
    "Esit Eket",
    "Essien Udim",
    "Etim Ekpo",
    "Etinan",
    "Ibeno",
    "Ibiono Ibom",
    "Ika",
    "Ikono",
    "Ikot Abasi",
    "Ikot Ekpene",
    "Ini",
    "Itu",
    "Mbo",
    "Mkpat Enin",
    "Nsit Atai",
    "Nsit Ibom",
    "Obot Akara",
    "Okobo",
    "Onna",
    "Oron",
    "Oruk Anam",
    "Uruan",
    "Urue Offong/Oruko",
    "Uyo"
  ],
  "Anambra": [
    "Aguata",
    "Awka North",
    "Awka South",
    "Dunukofia",
    "Ekwusigo",
    "Idemili North",
    "Idemili South",
    "Ihiala",
    "Njikoka",
    "Nnewi North",
    "Nnewi South",
    "Ogbaru",
    "Onitsha North",
    "Onitsha South",
    "Orumba North",
    "Orumba South",
    "Oyi"
  ],
  "Bauchi": [
    "Alkaleri",
    "Bauchi",
    "Bogoro",
    "Damban",
    "Darazo",
    "Dass",
    "Gamawa",
    "Ganjuwa",
    "Katagum",
    "Misau",
    "Ningi",
    "Shira",
    "Tafawa Balewa",
    "Toro",
    "Warji",
    "Zaki"
  ],
  "Bayelsa": [
    "Brass",
    "Ekeremor",
    "Kolokuma/Opokuma",
    "Nembe",
    "Ogbia",
    "Sagbama",
    "Southern Ijaw",
    "Yenagoa"
  ],
  "Benue": [
    "Ado",
    "Agatu",
    "Apa",
    "Buruku",
    "Gboko",
    "Guma",
    "Gwer East",
    "Gwer West",
    "Katsina-Ala",
    "Konshisha",
    "Logo",
    "Makurdi",
    "Obi",
    "Ogbadibo",
    "Ohimini",
    "Otukpo",
    "Tarka",
    "Ukum",
    "Vandeikya"
  ],
  "Borno": [
    "Abadam",
    "Askira/Uba",
    "Bama",
    "Bayo",
    "Biu",
    "Chibok",
    "Damboa",
    "Dikwa",
    "Gubio",
    "Guzamala",
    "Hawul",
    "Jere",
    "Kaga",
    "Konduga",
    "Mafa",
    "Magumeri",
    "Maiduguri",
    "Ngala",
    "Nganzai",
    "Shani"
  ],
  "Cross River": [
    "Akpabuyo",
    "Bakassi",
    "Calabar Municipal",
    "Calabar South",
    "Ekureku",
    "Ikom",
    "Obanliku",
    "Obubra",
    "Odukpani",
    "Ogoja",
    "Yakuur",
    "Yala"
  ],
  "Delta": [
    "Aniocha North",
    "Aniocha South",
    "Bomadi",
    "Burutu",
    "Ethiope East",
    "Ethiope West",
    "Ika North East",
    "Ika South",
    "Okpe",
    "Oshimili North",
    "Oshimili South",
    "Patani",
    "Sapele",
    "Udu",
    "Ughelli North",
    "Ughelli South",
    "Warri North",
    "Warri South",
    "Warri South West"
  ],
  "Ebonyi": [
    "Abakaliki",
    "Afikpo North",
    "Afikpo South",
    "Ebonyi",
    "Ezza North",
    "Ezza South",
    "Ikwo",
    "Ishielu",
    "Ivo",
    "Ohaozara",
    "Ohaukwu",
    "Onicha"
  ],
  "Edo": [
    "Akoko Edo",
    "Esan Central",
    "Esan North-East",
    "Esan South-East",
    "Esan West",
    "Egor",
    "Igueben",
    "Ikpoba Okha",
    "Oredo",
    "Orhionmwon",
    "Ovia North-East",
    "Ovia South-West",
    "Uhunmwonde"
  ],
  "Ekiti": [
    "Ado Ekiti",
    "Ekiti East",
    "Ekiti South-West",
    "Ekiti West",
    "Emure",
    "Irepodun/Ifelodun",
    "Ise/Orun",
    "Moba",
    "Oye"
  ],
  "Enugu": [
    "Awgu",
    "Enugu East",
    "Enugu North",
    "Enugu South",
    "Igbo Etiti",
    "Igbo Eze North",
    "Igbo Eze South",
    "Isi Uzo",
    "Nkanu East",
    "Nkanu West",
    "Nsukka",
    "Oji River",
    "Udenu",
    "Udi",
    "Igbo Eze South"
  ],
  "FCT": [
    "Abaji",
    "Abuja Municipal",
    "Bwari",
    "Gwagwalada",
    "Kuje",
    "Kwali"
  ],
  "Gombe": [
    "Akko",
    "Balanga",
    "Billiri",
    "Dukku",
    "Funakaye",
    "Gombe",
    "Kaltungo",
    "Kwami",
    "Nafada",
    "Shongom",
    "Yamaltu/Deba"
  ],
  "Imo": [
    "Aboh Mbaise",
    "Ahiazu Mbaise",
    "Ehime Mbano",
    "Ezinihitte",
    "Ideato North",
    "Ideato South",
    "Ihitte/Uboma",
    "Isu",
    "Mbaitoli",
    "Ngor Okpala",
    "Njaba",
    "Nkwerre",
    "Nwangele",
    "Obowo",
    "Oguta",
    "Ohaji/Egbema",
    "Orlu",
    "Orsu",
    "Owerri Municipal",
    "Owerri North",
    "Owerri West"
  ],
  "Jigawa": [
    "Auyo",
    "Babura",
    "Birniwa",
    "Dutse",
    "Gagarawa",
    "Gumel",
    "Hadejia",
    "Jahun",
    "Kazaure",
    "Kiyawa",
    "Maigatari",
    "Miga",
    "Ringim",
    "Sule Tankarkar",
    "Yankwashi"
  ],
  "Kaduna": [
    "Birnin Gwari",
    "Chikun",
    "Giwa",
    "Igabi",
    "Jaba",
    "Jema'a",
    "Kachia",
    "Kaduna North",
    "Kaduna South",
    "Kagarko",
    "Kaura",
    "Kudan",
    "Lere",
    "Makarfi",
    "Sabon Gari",
    "Sanga",
    "Soba",
    "Zangon Kataf",
    "Zaria"
  ],
  "Kano": [
    "Ajingi",
    "Albasu",
    "Bagwai",
    "Bebeji",
    "Bichi",
    "Bunkure",
    "Dala",
    "Dambatta",
    "Dawakin Kudu",
    "Dawakin Tofa",
    "Gaya",
    "Gezawa",
    "Gwarzo",
    "Kano Municipal",
    "Karaye",
    "Kibiya",
    "Kumbotso",
    "Madobi",
    "Makoda",
    "Minjibir",
    "Nasarawa",
    "Rogo",
    "Shanono",
    "Sumaila",
    "Tofa",
    "Tsanyawa",
    "Tudun Wada",
    "Ungogo",
    "Warawa",
    "Wudil"
  ],
  "Kogi": [
    "Adavi",
    "Ajaokuta",
    "Ankpa",
    "Bassa",
    "Dekina",
    "Ibaji",
    "Idah",
    "Igalamela/Odolu",
    "Ijumu",
    "Okene",
    "Okehi",
    "Ogori/Magongo",
    "Olamaboro",
    "Yagba East",
    "Yagba West"
  ],
  "Kwara": [
    "Asa",
    "Baruten",
    "Ekiti",
    "Ifelodun",
    "Ilorin East",
    "Ilorin South",
    "Ilorin West",
    "Irepodun",
    "Isin",
    "Offa",
    "Oke Ero",
    "Oyun",
    "Patigi"
  ],
  "Lagos": [
    "Agege",
    "Ajeromi-Ifelodun",
    "Alimosho",
    "Amuwo-Odofin",
    "Apapa",
    "Badagry",
    "Bakare",
    "Bariga",
    "Epe",
    "Eti-Osa",
    "Ibeju-Lekki",
    "Ifako-Ijaiye",
    "Ikeja",
    "Ikorodu",
    "Lagos Island",
    "Lagos Mainland",
    "Mushin",
    "Ojo",
    "Oshodi-Isolo",
    "Somolu",
    "Surulere"
  ],
  "Nasarawa": [
    "Akwanga",
    "Doma",
    "Karshi",
    "Keana",
    "Keffi",
    "Nasarawa",
    "Obi",
    "Toto",
    "Wamba"
  ],
  "Niger": [
    "Agwara",
    "Bida",
    "Borgu",
    "Bosso",
    "Chanchaga",
    "Edati",
    "Gbako",
    "Gurara",
    "Katcha",
    "Lapai",
    "Lavun",
    "Mokwa",
    "Niger",
    "Rafi",
    "Shiroro",
    "Suleja",
    "Tafa",
    "Wushishi"
  ],
  "Ogun": [
    "Abeokuta North",
    "Abeokuta South",
    "Ado-Odo/Ota",
    "Egbado North",
    "Egbado South",
    "Ifo",
    "Ijebu East",
    "Ijebu North",
    "Ijebu North East",
    "Ijebu Ode",
    "Obafemi Owode",
    "Odeda",
    "Odogbolu",
    "Remo North",
    "Sagamu",
    "Yewa North",
    "Yewa South"
  ],
  "Ondo": [
    "Akoko North-East",
    "Akoko North-West",
    "Akoko South-East",
    "Akoko South-West",
    "Akure North",
    "Akure South",
    "Ese Odo",
    "Idanre",
    "Ifedore",
    "Ilaje",
    "Odigbo",
    "Owo"
  ],
  "Osun": [
    "Aiyedade",
    "Aiyedire",
    "Atakunmosa East",
    "Atakunmosa West",
    "Boluwaduro",
    "Boripe",
    "Ife East",
    "Ife North",
    "Ife South",
    "Ilesa East",
    "Ilesa West",
    "Irepodun",
    "Isokan",
    "Obokun",
    "Odo Otin",
    "Ola Oluwa",
    "Oriade",
    "Orolu",
    "Osogbo"
  ],
  "Oyo": [
    "Akinyele",
    "Atiba",
    "Atigbo",
    "Egbeda",
    "Ibadan North",
    "Ibadan North East",
    "Ibadan South East",
    "Ibadan South West",
    "Ibarapa Central",
    "Ibarapa East",
    "Ibarapa North",
    "Ido",
    "Iseyin",
    "Itesiwaju",
    "Ogbomosho North",
    "Ogbomosho South",
    "Oyo East",
    "Oyo West",
    "Saki East",
    "Saki West",
    "Surulere"
  ],
  "Plateau": [
    "Bokkos",
    "Jos East",
    "Jos North",
    "Jos South",
    "Kanam",
    "Kanke",
    "Langtang North",
    "Langtang South",
    "Mangu",
    "Pankshin",
    "Quaan Pan",
    "Riyom",
    "Shendam",
    "Wase"
  ],
  "Rivers": [
    "Abua/Odual",
    "Ahoada East",
    "Ahoada West",
    "Akuku-Toru",
    "Asari-Toru",
    "Bonny",
    "Degema",
    "Emohua",
    "Etche",
    "Ikwerre",
    "Obio/Akpor",
    "Ogba/Egbema/Ndoni",
    "Ogu/Bolo",
    "Port Harcourt",
    "Tai"
  ],
  "Sokoto": [
    "Binji",
    "Bodinga",
    "Dange Shuni",
    "Gada",
    "Goronyo",
    "Gudu",
    "Illela",
    "Kebbe",
    "Kware",
    "Rabah",
    "Sokoto North",
    "Sokoto South",
    "Tambuwal",
    "Wamakko",
    "Wurno",
    "Yabo"
  ],
  "Taraba": [
    "Ardo Kola",
    "Bali",
    "Donga",
    "Gashaka",
    "Gassol",
    "Jalingo",
    "Karim Lamido",
    "Kona",
    "Lau",
    "Sardauna",
    "Takum",
    "Ussa",
    "Wukari"
  ],
  "Yobe": [
    "Bade",
    "Bursari",
    "Damaturu",
    "Fika",
    "Fune",
    "Geidam",
    "Gujba",
    "Jakusko",
    "Karasuwa",
    "Machina",
    "Nangere",
    "Nguru",
    "Potiskum",
    "Tarmuwa",
    "Yunusari"
  ],
  "Zamfara": [
    "Anka",
    "Bakura",
    "Birnin Magaji",
    "Bukkuyum",
    "Gummi",
    "Gusau",
    "Isa",
    "Kaura Namoda",
    "Maradun",
    "Shinkafi",
    "Talata Mafara",
    "Zamfara"
  ]
}; 