-- Baseline: the schema this project was actually built with.
--
-- WHY THIS FILE EXISTS
--
-- This project was built through the Supabase dashboard, not the CLI. As a
-- result supabase_migrations.schema_migrations in production held ZERO rows,
-- and no migration in this repository ever created the core tables: sales,
-- organizations, profiles, stove_ids_base, addresses or uploads. Every later
-- migration alters tables that nothing creates.
--
-- The practical cost was that no environment could be stood up from this
-- repository at all. Supabase branching builds a preview database by running
-- these migrations against an empty Postgres, so branching could not work, and
-- the local stack was missing the auth triggers for the same reason.
--
-- This is the step Supabase documents as "Preparing your Git repository":
-- supabase db pull, then commit. It was never done. This file is that.
--
-- CONTENTS
--
-- 1. schema-baselines/sales_public_baseline.sql, an introspection of the live
--    public schema: extensions, tables, constraints, indexes, RLS policies,
--    functions and views.
-- 2. schema-baselines/sales_supplemental_baseline.sql: auth trigger functions,
--    the auth.users triggers, and storage buckets and policies.
--
-- Timestamped 00000000000000 so it runs before every existing migration. Those
-- migrations then re-apply on top harmlessly: they are guarded with IF EXISTS
-- or IF NOT EXISTS, and every destructive statement in the partner-purge pair
-- is commented out. Verified, not assumed.
--
-- DELIBERATELY EXCLUDED: public.backup_partpaid_outright_20260815, a dated
-- one-off backup table present in production. It is operational debris rather
-- than schema, so a rebuilt environment should not carry it.
--
-- PRODUCTION MUST HAVE THIS MARKED APPLIED, NEVER RUN:
--   supabase migration repair --status applied 00000000000000

-- Baseline schema snapshot: SALES (oeiwnpngbnkhcismhpgs)
-- Generated by introspection via the Supabase Management API.
-- Public schema only. Supabase-managed schemas (auth, storage, ...) are
-- created by the local stack itself and are deliberately not included.
-- Read-only extraction: production was never modified.

set check_function_bodies = off;

-- ============ extensions ============
create extension if not exists "pg_cron" with schema "pg_catalog";
create extension if not exists "pg_net" with schema "public";
create extension if not exists "pg_stat_statements" with schema "extensions";
create extension if not exists "pgcrypto" with schema "extensions";
create extension if not exists "supabase_vault" with schema "vault";
create extension if not exists "uuid-ossp" with schema "extensions";

-- ============ custom schemas ============
create schema if not exists "purge_archive";

-- ============ enum types ============

-- ============ sequences ============

-- ============ tables ============
create table if not exists public."acsl_agent_organizations" (
  "id" uuid default gen_random_uuid() not null,
  "agent_id" uuid not null,
  "organization_id" uuid not null,
  "assigned_by" uuid not null,
  "assigned_at" timestamp with time zone default now() not null
);
create table if not exists public."acsl_agent_states" (
  "id" uuid default gen_random_uuid() not null,
  "agent_id" uuid not null,
  "state" text not null,
  "assigned_by" uuid not null,
  "assigned_at" timestamp with time zone default now() not null
);
create table if not exists public."addresses" (
  "id" uuid default gen_random_uuid() not null,
  "full_address" text,
  "street" text,
  "city" text,
  "state" text,
  "country" text,
  "latitude" double precision,
  "longitude" double precision,
  "created_at" timestamp without time zone default now()
);
create table if not exists public."app_releases" (
  "id" uuid default '00000000-0000-0000-0000-000000000002'::uuid not null,
  "version" text default '1.0.0'::text not null,
  "release_notes" text default ''::text not null,
  "base_url" text default ''::text not null,
  "apk_path" text default '/downloads/sales-monitoring-app.apk'::text not null,
  "is_force_update" boolean default false not null,
  "size" text default '~45 MB'::text not null,
  "requires" text default 'Android 8.0+'::text not null,
  "features" jsonb default '[]'::jsonb not null,
  "requirements" jsonb default '[]'::jsonb not null,
  "updated_at" timestamp with time zone default now() not null
);
create table if not exists public."app_settings" (
  "id" uuid default gen_random_uuid() not null,
  "google_places_api_key" text,
  "brevo_api_key" text,
  "updated_at" timestamp with time zone default now(),
  "updated_by" uuid,
  "google_maps_api_key" text
);
create table if not exists public."cancelled_purchases" (
  "id" uuid default gen_random_uuid() not null,
  "original_transfer_id" uuid,
  "transaction_id" text,
  "organization_id" uuid,
  "partner_id" text,
  "partner_name" text,
  "state" text,
  "branch" text,
  "sales_factory" text,
  "sales_date" date,
  "transfer_date" timestamp with time zone,
  "stove_count" integer default 0 not null,
  "stove_ids_snapshot" jsonb default '[]'::jsonb not null,
  "cancellation_reason" text not null,
  "cancelled_by" uuid,
  "cancelled_at" timestamp with time zone default now() not null
);
create table if not exists public."credentials" (
  "id" uuid default gen_random_uuid() not null,
  "partner_id" character varying(255),
  "partner_name" character varying(255) not null,
  "email" character varying(255) not null,
  "password" text not null,
  "organization_id" uuid,
  "user_id" uuid,
  "is_dummy_email" boolean default true,
  "created_at" timestamp with time zone default now(),
  "updated_at" timestamp with time zone default now(),
  "username" text,
  "role" text default 'admin'::text,
  "profile_id" uuid
);
create table if not exists public."email_config" (
  "id" uuid default gen_random_uuid() not null,
  "resend_api_key" text,
  "sender_name" text default 'Atmosfair Sales'::text,
  "sender_email" text default 'no-reply@atmosfair.com'::text,
  "is_configured" boolean default false,
  "updated_by" uuid,
  "updated_at" timestamp with time zone default now(),
  "created_at" timestamp with time zone default now()
);
create table if not exists public."email_logs" (
  "id" uuid default gen_random_uuid() not null,
  "recipient_email" text not null,
  "recipient_name" text,
  "subject" text not null,
  "notification_key" text,
  "status" text default 'pending'::text not null,
  "error_message" text,
  "is_automatic" boolean default false,
  "resend_id" text,
  "created_at" timestamp with time zone default now()
);
create table if not exists public."external_app_tokens" (
  "id" uuid default gen_random_uuid() not null,
  "token" character varying(255) not null,
  "secret_key" character varying(255) not null,
  "application_name" character varying(255) not null,
  "application_description" text,
  "allowed_urls" text[],
  "is_active" boolean default true,
  "created_at" timestamp with time zone default now(),
  "last_used_at" timestamp with time zone,
  "usage_count" integer default 0
);
create table if not exists public."installment_payments" (
  "id" uuid default gen_random_uuid() not null,
  "sale_id" uuid not null,
  "amount" numeric(12,2) not null,
  "payment_method" text not null,
  "proof_image_url" text,
  "proof_image_id" uuid,
  "notes" text,
  "recorded_by" uuid not null,
  "payment_date" date default CURRENT_DATE not null,
  "created_at" timestamp with time zone default now() not null
);
create table if not exists public."nigeria_lgas" (
  "id" bigint generated always as identity not null,
  "state_name" text not null,
  "name" text not null,
  "updated_at" timestamp with time zone default now() not null
);
create table if not exists public."nigeria_states" (
  "name" text not null,
  "updated_at" timestamp with time zone default now() not null
);
create table if not exists public."organization_payment_models" (
  "id" uuid default gen_random_uuid() not null,
  "organization_id" uuid not null,
  "payment_model_id" uuid not null,
  "assigned_by" uuid,
  "assigned_at" timestamp with time zone default now() not null
);
create table if not exists public."organizations" (
  "id" uuid default gen_random_uuid() not null,
  "created_at" timestamp with time zone default now(),
  "contact_phone" text not null,
  "address" text,
  "state" character varying(100) not null,
  "updated_at" timestamp with time zone default now(),
  "created_by" uuid,
  "branch" character varying(100),
  "contact_person" character varying(100),
  "alternative_phone" text,
  "partner_name" character varying(100) not null,
  "email" character varying(255),
  "updated_by" uuid,
  "partner_id" text,
  "partner_type" text,
  "manually_edited" boolean default false not null
);
create table if not exists public."organizations_backup_20251002" (
  "id" uuid not null,
  "name" text,
  "created_at" timestamp with time zone,
  "partner_email" text,
  "contact_phone" text,
  "address" text,
  "city" text,
  "state" text,
  "country" text,
  "description" text,
  "status" text,
  "updated_at" timestamp with time zone,
  "created_by" uuid,
  "branch" text,
  "contact_person" text,
  "alternative_phone" text
);
create table if not exists public."payment_models" (
  "id" uuid default gen_random_uuid() not null,
  "name" text not null,
  "description" text,
  "duration_months" integer not null,
  "fixed_price" numeric(12,2) not null,
  "min_down_payment" numeric(12,2) default 0,
  "is_active" boolean default true not null,
  "created_by" uuid,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);
create table if not exists public."profiles" (
  "id" uuid default gen_random_uuid() not null,
  "created_at" timestamp with time zone default now() not null,
  "email" text,
  "full_name" text,
  "phone" text,
  "role" text,
  "has_changed_password" boolean,
  "organization_id" uuid,
  "username" text,
  "status" text default 'active'::text,
  "last_login" timestamp with time zone,
  "updated_at" timestamp with time zone,
  "updated_by" uuid,
  "manager_id" uuid
);
create table if not exists public."sales" (
  "id" uuid default gen_random_uuid() not null,
  "transaction_id" text,
  "stove_serial_no" text,
  "sales_date" date,
  "contact_person" text,
  "contact_phone" text,
  "end_user_name" text,
  "aka" text,
  "state_backup" text,
  "lga_backup" text,
  "phone" text,
  "other_phone" text,
  "partner_name" text,
  "amount" numeric,
  "signature" text,
  "created_by" uuid,
  "organization_id" uuid,
  "address_id" uuid,
  "stove_image_id" uuid,
  "agreement_image_id" uuid,
  "created_at" timestamp without time zone default now(),
  "status" text default 'incomplete'::text not null,
  "agent_approved" boolean default false,
  "agent_approved_at" timestamp with time zone,
  "agent_approved_by" uuid,
  "is_installment" boolean default false not null,
  "payment_model_id" uuid,
  "total_paid" numeric(12,2) default 0,
  "payment_status" text default 'not_applicable'::text,
  "retailer_branch" text,
  "pot_quantity" integer,
  "heat_retention_device" boolean default false,
  "previous_stove_type" text,
  "previous_stove_other" text,
  "meals_per_day" text,
  "cooking_fuel_source" text,
  "cooking_location" text,
  "terms_accepted" jsonb,
  "is_archived" boolean default false,
  "platform" text default 'web'::text not null,
  "sold_on_behalf_of" uuid,
  "cancelled_at" timestamp with time zone,
  "cancelled_by" uuid,
  "cancel_reason" text,
  "updated_at" timestamp with time zone,
  "updated_by" uuid
);
create table if not exists public."sales_history" (
  "id" uuid default gen_random_uuid() not null,
  "sale_id" uuid not null,
  "action_type" character varying(50) not null,
  "action_description" text not null,
  "field_changes" jsonb,
  "performed_by" uuid not null,
  "performed_at" timestamp with time zone default now(),
  "ip_address" inet,
  "user_agent" text,
  "created_at" timestamp with time zone default now(),
  "updated_at" timestamp with time zone default now()
);
create table if not exists public."sales_images" (
  "id" uuid default gen_random_uuid() not null,
  "type" text,
  "public_id" text,
  "url" text,
  "created_at" timestamp without time zone default now()
);
create table if not exists public."stove_ids_base" (
  "id" uuid default gen_random_uuid() not null,
  "stove_id" text not null,
  "organization_id" uuid not null,
  "status" text default 'available'::text not null,
  "created_at" timestamp with time zone default now(),
  "sale_id" uuid,
  "factory" text,
  "is_archived" boolean default false,
  "archive_note" text,
  "sales_reference" text,
  "transfer_sales_date" date
);
create table if not exists public."stove_transfer_history" (
  "id" uuid default gen_random_uuid() not null,
  "transaction_id" text not null,
  "organization_id" uuid,
  "partner_name" text not null,
  "partner_id" text not null,
  "state" text,
  "branch" text,
  "stove_count" integer default 0 not null,
  "stove_ids" jsonb default '[]'::jsonb not null,
  "source" text not null,
  "application_name" text,
  "transfer_date" timestamp with time zone default now() not null,
  "created_at" timestamp with time zone default now() not null,
  "sales_factory" text,
  "sales_date" date,
  "customer" text,
  "downloaded_by" text,
  "sales_rep" text
);
create table if not exists public."sync_logs" (
  "id" uuid default gen_random_uuid() not null,
  "source" text not null,
  "status" text not null,
  "application_name" text,
  "started_at" timestamp with time zone default now() not null,
  "completed_at" timestamp with time zone,
  "duration_ms" integer,
  "total_partners" integer default 0,
  "partners_created" integer default 0,
  "partners_updated" integer default 0,
  "partners_failed" integer default 0,
  "total_stove_ids" integer default 0,
  "stove_ids_created" integer default 0,
  "stove_ids_skipped" integer default 0,
  "entries" jsonb default '[]'::jsonb,
  "request_summary" jsonb,
  "error_message" text,
  "created_at" timestamp with time zone default now() not null
);
create table if not exists public."uploads" (
  "id" uuid default gen_random_uuid() not null,
  "public_id" text,
  "url" text,
  "type" text,
  "created_by" uuid,
  "created_at" timestamp without time zone default now()
);

-- ============ constraints ============
alter table public."acsl_agent_organizations" add constraint "super_admin_agent_organizations_pkey" PRIMARY KEY (id);
alter table public."acsl_agent_states" add constraint "super_admin_agent_states_pkey" PRIMARY KEY (id);
alter table public."addresses" add constraint "addresses_pkey" PRIMARY KEY (id);
alter table public."app_releases" add constraint "app_releases_pkey" PRIMARY KEY (id);
alter table public."app_settings" add constraint "app_settings_pkey" PRIMARY KEY (id);
alter table public."cancelled_purchases" add constraint "cancelled_purchases_pkey" PRIMARY KEY (id);
alter table public."credentials" add constraint "credentials_pkey" PRIMARY KEY (id);
alter table public."email_config" add constraint "email_config_pkey" PRIMARY KEY (id);
alter table public."email_logs" add constraint "email_logs_pkey" PRIMARY KEY (id);
alter table public."external_app_tokens" add constraint "external_app_tokens_pkey" PRIMARY KEY (id);
alter table public."installment_payments" add constraint "installment_payments_pkey" PRIMARY KEY (id);
alter table public."nigeria_lgas" add constraint "nigeria_lgas_pkey" PRIMARY KEY (id);
alter table public."nigeria_states" add constraint "nigeria_states_pkey" PRIMARY KEY (name);
alter table public."organization_payment_models" add constraint "organization_payment_models_pkey" PRIMARY KEY (id);
alter table public."organizations" add constraint "organizations_pkey" PRIMARY KEY (id);
alter table public."organizations_backup_20251002" add constraint "organizations_backup_20251002_pkey" PRIMARY KEY (id);
alter table public."payment_models" add constraint "payment_models_pkey" PRIMARY KEY (id);
alter table public."profiles" add constraint "profiles_pkey" PRIMARY KEY (id);
alter table public."sales" add constraint "sales_pkey" PRIMARY KEY (id);
alter table public."sales_history" add constraint "sales_history_pkey" PRIMARY KEY (id);
alter table public."sales_images" add constraint "sales_images_pkey" PRIMARY KEY (id);
alter table public."stove_ids_base" add constraint "stove_ids_pkey" PRIMARY KEY (id);
alter table public."stove_transfer_history" add constraint "stove_transfer_history_pkey" PRIMARY KEY (id);
alter table public."sync_logs" add constraint "sync_logs_pkey" PRIMARY KEY (id);
alter table public."uploads" add constraint "uploads_pkey" PRIMARY KEY (id);
alter table public."acsl_agent_organizations" add constraint "super_admin_agent_organizations_agent_id_organization_id_key" UNIQUE (agent_id, organization_id);
alter table public."acsl_agent_states" add constraint "super_admin_agent_states_agent_id_state_key" UNIQUE (agent_id, state);
alter table public."credentials" add constraint "credentials_email_key" UNIQUE (email);
alter table public."credentials" add constraint "credentials_partner_id_key" UNIQUE (partner_id);
alter table public."external_app_tokens" add constraint "external_app_tokens_token_key" UNIQUE (token);
alter table public."nigeria_lgas" add constraint "nigeria_lgas_state_name_name_key" UNIQUE (state_name, name);
alter table public."organization_payment_models" add constraint "organization_payment_models_organization_id_payment_model_i_key" UNIQUE (organization_id, payment_model_id);
alter table public."profiles" add constraint "profiles_email_key" UNIQUE (email);
alter table public."profiles" add constraint "profiles_username_key" UNIQUE (username);
alter table public."stove_ids_base" add constraint "stove_ids_stove_id_organization_id_key" UNIQUE (stove_id, organization_id);
alter table public."installment_payments" add constraint "installment_payments_payment_method_check" CHECK ((payment_method = ANY (ARRAY['cash'::text, 'transfer'::text, 'pos'::text])));
alter table public."organizations" add constraint "organizations_partner_type_check" CHECK (((partner_type IS NULL) OR (partner_type = ANY (ARRAY['partner'::text, 'customer'::text]))));
alter table public."profiles" add constraint "profiles_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'disabled'::text])));
alter table public."sales" add constraint "sales_payment_status_check" CHECK ((payment_status = ANY (ARRAY['not_applicable'::text, 'partially_paid'::text, 'fully_paid'::text])));
alter table public."sales" add constraint "sales_platform_check" CHECK ((platform = ANY (ARRAY['web'::text, 'mobile'::text])));
alter table public."sales" add constraint "sales_status_check" CHECK ((status = ANY (ARRAY['incomplete'::text, 'completed'::text, 'pending'::text, 'assigned'::text])));
alter table public."sales_images" add constraint "sales_images_type_check" CHECK ((type = ANY (ARRAY['stove'::text, 'agreement'::text])));
alter table public."stove_ids_base" add constraint "stove_ids_sale_id_check" CHECK ((((status = 'sold'::text) AND (sale_id IS NOT NULL)) OR (status <> 'sold'::text)));
alter table public."stove_transfer_history" add constraint "stove_transfer_history_source_check" CHECK ((source = ANY (ARRAY['external-sync'::text, 'external-csv-sync'::text])));
alter table public."sync_logs" add constraint "sync_logs_source_check" CHECK ((source = ANY (ARRAY['external-sync'::text, 'external-csv-sync'::text])));
alter table public."sync_logs" add constraint "sync_logs_status_check" CHECK ((status = ANY (ARRAY['success'::text, 'partial'::text, 'failed'::text])));
alter table public."acsl_agent_organizations" add constraint "super_admin_agent_organizations_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."acsl_agent_organizations" add constraint "super_admin_agent_organizations_assigned_by_fkey" FOREIGN KEY (assigned_by) REFERENCES profiles(id);
alter table public."acsl_agent_organizations" add constraint "super_admin_agent_organizations_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public."acsl_agent_states" add constraint "super_admin_agent_states_agent_id_fkey" FOREIGN KEY (agent_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."acsl_agent_states" add constraint "super_admin_agent_states_assigned_by_fkey" FOREIGN KEY (assigned_by) REFERENCES profiles(id);
alter table public."app_settings" add constraint "app_settings_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id);
alter table public."cancelled_purchases" add constraint "cancelled_purchases_cancelled_by_fkey" FOREIGN KEY (cancelled_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public."credentials" add constraint "credentials_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public."credentials" add constraint "credentials_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public."credentials" add constraint "fk_credentials_profile" FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public."email_config" add constraint "email_config_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id);
alter table public."installment_payments" add constraint "installment_payments_proof_image_id_fkey" FOREIGN KEY (proof_image_id) REFERENCES uploads(id);
alter table public."installment_payments" add constraint "installment_payments_recorded_by_fkey" FOREIGN KEY (recorded_by) REFERENCES profiles(id);
alter table public."installment_payments" add constraint "installment_payments_sale_id_fkey" FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE;
alter table public."nigeria_lgas" add constraint "nigeria_lgas_state_name_fkey" FOREIGN KEY (state_name) REFERENCES nigeria_states(name) ON UPDATE CASCADE ON DELETE CASCADE;
alter table public."organization_payment_models" add constraint "organization_payment_models_assigned_by_fkey" FOREIGN KEY (assigned_by) REFERENCES profiles(id);
alter table public."organization_payment_models" add constraint "organization_payment_models_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public."organization_payment_models" add constraint "organization_payment_models_payment_model_id_fkey" FOREIGN KEY (payment_model_id) REFERENCES payment_models(id) ON DELETE CASCADE;
alter table public."organizations" add constraint "organizations_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public."organizations" add constraint "organizations_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id);
alter table public."payment_models" add constraint "payment_models_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id);
alter table public."profiles" add constraint "profiles_manager_id_fkey" FOREIGN KEY (manager_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public."profiles" add constraint "profiles_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public."profiles" add constraint "profiles_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public."sales" add constraint "sales_address_id_fkey" FOREIGN KEY (address_id) REFERENCES addresses(id);
alter table public."sales" add constraint "sales_agent_approved_by_fkey" FOREIGN KEY (agent_approved_by) REFERENCES profiles(id);
alter table public."sales" add constraint "sales_agreement_image_id_fkey" FOREIGN KEY (agreement_image_id) REFERENCES uploads(id);
alter table public."sales" add constraint "sales_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public."sales" add constraint "sales_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public."sales" add constraint "sales_payment_model_id_fkey" FOREIGN KEY (payment_model_id) REFERENCES payment_models(id);
alter table public."sales" add constraint "sales_sold_on_behalf_of_fkey" FOREIGN KEY (sold_on_behalf_of) REFERENCES profiles(id);
alter table public."sales" add constraint "sales_stove_image_id_fkey" FOREIGN KEY (stove_image_id) REFERENCES uploads(id);
alter table public."sales" add constraint "sales_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public."sales_history" add constraint "sales_history_performed_by_fkey" FOREIGN KEY (performed_by) REFERENCES auth.users(id);
alter table public."sales_history" add constraint "sales_history_sale_id_fkey" FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE;
alter table public."stove_ids_base" add constraint "stove_ids_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public."stove_ids_base" add constraint "stove_ids_sale_id_fkey" FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE SET NULL;
alter table public."stove_transfer_history" add constraint "stove_transfer_history_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public."uploads" add constraint "uploads_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;

-- ============ indexes ============
CREATE INDEX IF NOT EXISTS idx_cancelled_purchases_cancelled_at ON public.cancelled_purchases USING btree (cancelled_at DESC);
CREATE INDEX IF NOT EXISTS idx_credentials_email ON public.credentials USING btree (email);
CREATE INDEX IF NOT EXISTS idx_credentials_is_dummy_email ON public.credentials USING btree (is_dummy_email);
CREATE INDEX IF NOT EXISTS idx_credentials_organization_id ON public.credentials USING btree (organization_id);
CREATE INDEX IF NOT EXISTS idx_credentials_partner_id ON public.credentials USING btree (partner_id);
CREATE INDEX IF NOT EXISTS idx_credentials_profile_id ON public.credentials USING btree (profile_id);
CREATE INDEX IF NOT EXISTS idx_credentials_role ON public.credentials USING btree (role);
CREATE INDEX IF NOT EXISTS idx_credentials_user_id ON public.credentials USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_external_app_tokens_active ON public.external_app_tokens USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_external_app_tokens_token ON public.external_app_tokens USING btree (token);
CREATE INDEX IF NOT EXISTS idx_installment_payments_recorded_by ON public.installment_payments USING btree (recorded_by);
CREATE INDEX IF NOT EXISTS idx_installment_payments_sale_id ON public.installment_payments USING btree (sale_id);
CREATE INDEX IF NOT EXISTS idx_org_payment_models_model_id ON public.organization_payment_models USING btree (payment_model_id);
CREATE INDEX IF NOT EXISTS idx_org_payment_models_org_id ON public.organization_payment_models USING btree (organization_id);
CREATE INDEX IF NOT EXISTS idx_organizations_branch ON public.organizations USING btree (branch);
CREATE INDEX IF NOT EXISTS idx_organizations_contact_phone ON public.organizations USING btree (contact_phone);
CREATE INDEX IF NOT EXISTS idx_organizations_created_at ON public.organizations USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_organizations_created_by ON public.organizations USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_organizations_partner_name ON public.organizations USING btree (partner_name);
CREATE INDEX IF NOT EXISTS idx_organizations_partner_type ON public.organizations USING btree (partner_type);
CREATE INDEX IF NOT EXISTS idx_organizations_state ON public.organizations USING btree (state);
CREATE INDEX IF NOT EXISTS idx_organizations_updated_by ON public.organizations USING btree (updated_by);
CREATE INDEX IF NOT EXISTS idx_payment_models_is_active ON public.payment_models USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_profiles_manager_id ON public.profiles USING btree (manager_id);
CREATE INDEX IF NOT EXISTS idx_profiles_organization_id ON public.profiles USING btree (organization_id);
CREATE INDEX IF NOT EXISTS idx_profiles_role_status ON public.profiles USING btree (role, status);
CREATE INDEX IF NOT EXISTS idx_profiles_status ON public.profiles USING btree (status);
CREATE INDEX IF NOT EXISTS idx_profiles_username ON public.profiles USING btree (username);
CREATE INDEX IF NOT EXISTS idx_saao_agent_id ON public.acsl_agent_organizations USING btree (agent_id);
CREATE INDEX IF NOT EXISTS idx_saao_org_id ON public.acsl_agent_organizations USING btree (organization_id);
CREATE INDEX IF NOT EXISTS idx_saas_agent_id ON public.acsl_agent_states USING btree (agent_id);
CREATE INDEX IF NOT EXISTS idx_saas_state ON public.acsl_agent_states USING btree (state);
CREATE INDEX IF NOT EXISTS idx_sales_agent_approved ON public.sales USING btree (agent_approved) WHERE (agent_approved = false);
CREATE INDEX IF NOT EXISTS idx_sales_history_action_type ON public.sales_history USING btree (action_type);
CREATE INDEX IF NOT EXISTS idx_sales_history_performed_at ON public.sales_history USING btree (performed_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_history_performed_by ON public.sales_history USING btree (performed_by);
CREATE INDEX IF NOT EXISTS idx_sales_history_sale_id ON public.sales_history USING btree (sale_id);
CREATE INDEX IF NOT EXISTS idx_sales_is_archived ON public.sales USING btree (is_archived);
CREATE INDEX IF NOT EXISTS idx_sales_is_installment ON public.sales USING btree (is_installment);
CREATE INDEX IF NOT EXISTS idx_sales_organization_status ON public.sales USING btree (organization_id, status);
CREATE INDEX IF NOT EXISTS idx_sales_payment_model_id ON public.sales USING btree (payment_model_id);
CREATE INDEX IF NOT EXISTS idx_sales_payment_status ON public.sales USING btree (payment_status);
CREATE INDEX IF NOT EXISTS idx_sales_sold_on_behalf_of ON public.sales USING btree (sold_on_behalf_of);
CREATE INDEX IF NOT EXISTS idx_sales_status ON public.sales USING btree (status);
CREATE INDEX IF NOT EXISTS idx_stove_ids_factory ON public.stove_ids_base USING btree (factory);
CREATE INDEX IF NOT EXISTS idx_stove_ids_is_archived ON public.stove_ids_base USING btree (is_archived);
CREATE INDEX IF NOT EXISTS idx_stove_ids_sales_reference ON public.stove_ids_base USING btree (sales_reference);
CREATE INDEX IF NOT EXISTS idx_sync_logs_application_name ON public.sync_logs USING btree (application_name);
CREATE INDEX IF NOT EXISTS idx_sync_logs_source ON public.sync_logs USING btree (source);
CREATE INDEX IF NOT EXISTS idx_sync_logs_started_at ON public.sync_logs USING btree (started_at DESC);
CREATE INDEX IF NOT EXISTS idx_sync_logs_status ON public.sync_logs USING btree (status);
CREATE INDEX IF NOT EXISTS nigeria_lgas_state_idx ON public.nigeria_lgas USING btree (state_name);
CREATE INDEX IF NOT EXISTS organization_payment_models_organization_id_idx ON public.organization_payment_models USING btree (organization_id);
CREATE INDEX IF NOT EXISTS stove_transfer_history_organization_id_idx ON public.stove_transfer_history USING btree (organization_id);
CREATE INDEX IF NOT EXISTS stove_transfer_history_transfer_date_idx ON public.stove_transfer_history USING btree (transfer_date DESC);
CREATE UNIQUE INDEX IF NOT EXISTS organizations_partner_id_key ON public.organizations USING btree (partner_id) WHERE (partner_id IS NOT NULL);

-- ============ views ============
create or replace view public."stove_ids" as
 SELECT id,
    stove_id,
    organization_id,
    status,
    created_at,
    sale_id,
    factory,
    is_archived,
    archive_note,
    sales_reference,
    transfer_sales_date
   FROM stove_ids_base
  WHERE transfer_sales_date IS NULL OR transfer_sales_date >= '2026-01-01'::date;
create or replace view public."super_admin_agent_organizations" as
 SELECT id,
    agent_id,
    organization_id,
    assigned_by,
    assigned_at
   FROM acsl_agent_organizations;
create or replace view public."super_admin_agent_states" as
 SELECT id,
    agent_id,
    state,
    assigned_by,
    assigned_at
   FROM acsl_agent_states;
create or replace view public."user_org_context" as
 SELECT id AS user_id,
    organization_id
   FROM profiles;
create or replace view public."user_roles" as
 SELECT id,
    role
   FROM profiles;

-- ============ functions ============
CREATE OR REPLACE FUNCTION public.add_custom_sales_history(p_sale_id uuid, p_action_type character varying, p_action_description text, p_field_changes jsonb DEFAULT '{}'::jsonb)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    history_id UUID;
BEGIN
    INSERT INTO sales_history (
        sale_id,
        action_type,
        action_description,
        field_changes,
        performed_by,
        performed_at
    ) VALUES (
        p_sale_id,
        p_action_type,
        p_action_description,
        p_field_changes,
        auth.uid(),
        NOW()
    ) RETURNING id INTO history_id;
    
    RETURN history_id;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.apply_stove_field_backfill(rows jsonb, do_overwrite boolean DEFAULT false, dry_run boolean DEFAULT true)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  result jsonb;
BEGIN
  CREATE TEMP TABLE _bf (
    stove_id            text,
    sales_reference     text,
    transfer_sales_date date,
    factory             text
  ) ON COMMIT DROP;

  -- Parse incoming rows; tolerate bad dates (left NULL rather than erroring).
  INSERT INTO _bf
  SELECT
    x.stove_id,
    nullif(btrim(x.sales_reference), ''),
    CASE WHEN btrim(x.sales_date) ~ '^\d{4}-\d{2}-\d{2}'
         THEN btrim(x.sales_date)::date ELSE NULL END,
    nullif(btrim(x.factory), '')
  FROM jsonb_to_recordset(rows)
    AS x(stove_id text, sales_reference text, sales_date text, factory text)
  WHERE nullif(btrim(x.stove_id), '') IS NOT NULL;

  -- Preview counts (matched rows in base, and per-field fill/overwrite).
  WITH j AS (
    SELECT b.*, s.stove_id AS matched,
           s.sales_reference     AS cur_ref,
           s.transfer_sales_date AS cur_date,
           s.factory             AS cur_factory
    FROM _bf b
    LEFT JOIN stove_ids_base s ON s.stove_id = b.stove_id
  )
  SELECT jsonb_build_object(
    'input_rows',          (SELECT count(*) FROM _bf),
    'matched',             count(*) FILTER (WHERE matched IS NOT NULL),
    'not_found_in_app',    count(*) FILTER (WHERE matched IS NULL),
    'sales_reference', jsonb_build_object(
      'would_fill',      count(*) FILTER (WHERE matched IS NOT NULL AND sales_reference IS NOT NULL AND cur_ref IS NULL),
      'would_overwrite', count(*) FILTER (WHERE matched IS NOT NULL AND sales_reference IS NOT NULL AND cur_ref IS NOT NULL AND cur_ref IS DISTINCT FROM sales_reference)
    ),
    'transfer_sales_date', jsonb_build_object(
      'would_fill',      count(*) FILTER (WHERE matched IS NOT NULL AND transfer_sales_date IS NOT NULL AND cur_date IS NULL),
      'would_overwrite', count(*) FILTER (WHERE matched IS NOT NULL AND transfer_sales_date IS NOT NULL AND cur_date IS NOT NULL AND cur_date IS DISTINCT FROM transfer_sales_date)
    ),
    'factory', jsonb_build_object(
      'would_fill',      count(*) FILTER (WHERE matched IS NOT NULL AND factory IS NOT NULL AND cur_factory IS NULL),
      'would_overwrite', count(*) FILTER (WHERE matched IS NOT NULL AND factory IS NOT NULL AND cur_factory IS NOT NULL AND cur_factory IS DISTINCT FROM factory)
    )
  ) INTO result
  FROM j;

  IF NOT dry_run THEN
    UPDATE stove_ids_base s
    SET
      sales_reference = CASE
        WHEN b.sales_reference IS NOT NULL AND (do_overwrite OR s.sales_reference IS NULL)
        THEN b.sales_reference ELSE s.sales_reference END,
      transfer_sales_date = CASE
        WHEN b.transfer_sales_date IS NOT NULL AND (do_overwrite OR s.transfer_sales_date IS NULL)
        THEN b.transfer_sales_date ELSE s.transfer_sales_date END,
      factory = CASE
        WHEN b.factory IS NOT NULL AND (do_overwrite OR s.factory IS NULL)
        THEN b.factory ELSE s.factory END
    FROM _bf b
    WHERE s.stove_id = b.stove_id;

    result := result || jsonb_build_object('applied', true);
  ELSE
    result := result || jsonb_build_object('applied', false);
  END IF;

  DROP TABLE IF EXISTS _bf;
  RETURN result;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.calculate_sale_status(sale_record sales)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
BEGIN
  -- Check if all required fields are filled
  IF sale_record.transaction_id IS NOT NULL 
     AND sale_record.stove_serial_no IS NOT NULL 
     AND sale_record.end_user_name IS NOT NULL 
     AND sale_record.phone IS NOT NULL 
     AND sale_record.amount IS NOT NULL 
     AND sale_record.address_id IS NOT NULL 
     AND sale_record.stove_image_id IS NOT NULL 
     AND sale_record.agreement_image_id IS NOT NULL 
     AND sale_record.signature IS NOT NULL THEN
    RETURN 'completed';
  ELSE
    RETURN 'incomplete';
  END IF;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.calculate_sale_status()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Define variables for status calculation
  DECLARE
    required_fields_complete BOOLEAN;
    has_signature BOOLEAN;
    has_stove_image BOOLEAN;
    has_agreement_image BOOLEAN;
    calculated_status TEXT;
  BEGIN
    -- Check if all required fields are present and not empty
    required_fields_complete := (
      NEW.transaction_id IS NOT NULL AND trim(NEW.transaction_id) != '' AND
      NEW.stove_serial_no IS NOT NULL AND trim(NEW.stove_serial_no) != '' AND
      NEW.sales_date IS NOT NULL AND
      NEW.contact_person IS NOT NULL AND trim(NEW.contact_person) != '' AND
      NEW.contact_phone IS NOT NULL AND trim(NEW.contact_phone) != '' AND
      NEW.end_user_name IS NOT NULL AND trim(NEW.end_user_name) != '' AND
      NEW.phone IS NOT NULL AND trim(NEW.phone) != '' AND
      NEW.partner_name IS NOT NULL AND trim(NEW.partner_name) != '' AND
      NEW.amount IS NOT NULL AND NEW.amount > 0
    );
    
    -- Check for signature
    has_signature := (NEW.signature IS NOT NULL AND trim(NEW.signature) != '');
    
    -- Check for images
    has_stove_image := (NEW.stove_image_id IS NOT NULL);
    has_agreement_image := (NEW.agreement_image_id IS NOT NULL);
    
    -- Calculate status based on completeness (don't override 'assigned' status)
    IF NEW.status != 'assigned' THEN
      IF required_fields_complete AND has_signature AND has_stove_image AND has_agreement_image THEN
        calculated_status := 'completed';
      ELSIF required_fields_complete AND (has_signature OR has_stove_image OR has_agreement_image) THEN
        calculated_status := 'pending';
      ELSE
        calculated_status := 'incomplete';
      END IF;
      
      -- Set the calculated status
      NEW.status := calculated_status;
    END IF;
    
    RETURN NEW;
  END;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.cancel_purchase(_transfer_id uuid, _reason text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  _is_admin boolean;
  _transfer public.stove_transfer_history%ROWTYPE;
  _stove_ids text[];
  _blocking_count integer;
  _new_id uuid;
BEGIN
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'super_admin')
  INTO _is_admin;
  IF NOT _is_admin THEN
    RAISE EXCEPTION 'Only super admins can cancel purchases';
  END IF;

  IF _reason IS NULL OR length(btrim(_reason)) < 5 THEN
    RAISE EXCEPTION 'A cancellation reason of at least 5 characters is required';
  END IF;

  SELECT * INTO _transfer FROM public.stove_transfer_history WHERE id = _transfer_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transfer % not found', _transfer_id;
  END IF;

  SELECT ARRAY(
    SELECT jsonb_array_elements(_transfer.stove_ids)->>'stove_id'
  ) INTO _stove_ids;

  IF _stove_ids IS NOT NULL AND array_length(_stove_ids, 1) IS NOT NULL THEN
    SELECT count(*) INTO _blocking_count
    FROM public.sales
    WHERE stove_serial_no = ANY(_stove_ids)
      AND COALESCE(is_archived, false) = false;

    IF _blocking_count > 0 THEN
      RAISE EXCEPTION 'Cannot cancel: % stove(s) are still tied to active sales', _blocking_count;
    END IF;
  END IF;

  INSERT INTO public.cancelled_purchases (
    original_transfer_id, transaction_id, organization_id, partner_id, partner_name,
    state, branch, sales_factory, sales_date, transfer_date,
    stove_count, stove_ids_snapshot, cancellation_reason, cancelled_by
  ) VALUES (
    _transfer.id, _transfer.transaction_id, _transfer.organization_id, _transfer.partner_id, _transfer.partner_name,
    _transfer.state, _transfer.branch, _transfer.sales_factory, _transfer.sales_date, _transfer.transfer_date,
    COALESCE(_transfer.stove_count, 0), COALESCE(_transfer.stove_ids, '[]'::jsonb), btrim(_reason), auth.uid()
  ) RETURNING id INTO _new_id;

  IF _stove_ids IS NOT NULL AND array_length(_stove_ids, 1) IS NOT NULL AND _transfer.organization_id IS NOT NULL THEN
    DELETE FROM public.stove_ids_base
    WHERE stove_id = ANY(_stove_ids)
      AND organization_id = _transfer.organization_id
      AND sale_id IS NULL;
  END IF;

  DELETE FROM public.stove_transfer_history WHERE id = _transfer_id;

  RETURN _new_id;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.check_profile_email_exists(p_email text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN EXISTS (
    SELECT 1 
    FROM public.profiles 
    WHERE email = p_email
  );
END;
$function$
;
CREATE OR REPLACE FUNCTION public.check_purchase_cancellable(_transfer_id uuid)
 RETURNS TABLE(stove_serial_no text, sales_reference text, sales_date date, partner_name text, sale_id uuid)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  _is_admin boolean;
  _stove_ids text[];
BEGIN
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'super_admin')
  INTO _is_admin;
  IF NOT _is_admin THEN
    RAISE EXCEPTION 'Only super admins can cancel purchases';
  END IF;

  SELECT ARRAY(
    SELECT jsonb_array_elements(t.stove_ids)->>'stove_id'
    FROM public.stove_transfer_history t
    WHERE t.id = _transfer_id
  ) INTO _stove_ids;

  IF _stove_ids IS NULL OR array_length(_stove_ids, 1) IS NULL THEN
    RETURN;
  END IF;

  RETURN QUERY
    SELECT s.stove_serial_no, s.transaction_id AS sales_reference, s.sales_date, s.partner_name, s.id
    FROM public.sales s
    WHERE s.stove_serial_no = ANY(_stove_ids)
      AND COALESCE(s.is_archived, false) = false;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.create_sales_history()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    action_type VARCHAR(50);
    action_description TEXT;
    field_changes JSONB := '{}'::jsonb;
    change_details TEXT[];
    user_context JSONB;
    user_id UUID;
BEGIN
    user_id := auth.uid();
    
    IF user_id IS NULL THEN
        user_id := current_setting('app.current_user_id', true)::UUID;
    END IF;
    
    IF user_id IS NULL THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    IF TG_OP = 'INSERT' THEN
        action_type := 'created';
        action_description := 'Sale created with transaction ID: ' || NEW.transaction_id;
        
        -- Store initial values (exclude large binary fields like signature)
        field_changes := jsonb_build_object(
            'new_values', row_to_json(NEW)::jsonb - 'signature',
            'initial_creation', true
        );
        
    ELSIF TG_OP = 'UPDATE' THEN
        IF OLD.status != NEW.status THEN
            CASE NEW.status
                WHEN 'completed' THEN
                    action_type := 'completed';
                    action_description := 'Sale marked as completed';
                WHEN 'assigned' THEN
                    action_type := 'assigned';
                    action_description := 'Sale assigned to agent';
                WHEN 'cancelled' THEN
                    action_type := 'cancelled';
                    action_description := 'Sale cancelled';
                ELSE
                    action_type := 'updated';
                    action_description := 'Sale status changed from ' || OLD.status || ' to ' || NEW.status;
            END CASE;
        ELSE
            action_type := 'updated';
            action_description := 'Sale details updated';
        END IF;
        
        SELECT jsonb_object_agg(field_name, changes)
        INTO field_changes
        FROM (
            SELECT 
                field_name,
                jsonb_build_object(
                    'old_value', old_value,
                    'new_value', new_value
                ) as changes
            FROM (
                SELECT 'transaction_id' as field_name, to_jsonb(OLD.transaction_id) as old_value, to_jsonb(NEW.transaction_id) as new_value
                WHERE OLD.transaction_id IS DISTINCT FROM NEW.transaction_id
                UNION ALL
                SELECT 'amount', to_jsonb(OLD.amount), to_jsonb(NEW.amount)
                WHERE OLD.amount IS DISTINCT FROM NEW.amount
                UNION ALL
                SELECT 'status', to_jsonb(OLD.status), to_jsonb(NEW.status)
                WHERE OLD.status IS DISTINCT FROM NEW.status
                UNION ALL
                SELECT 'contact_person', to_jsonb(OLD.contact_person), to_jsonb(NEW.contact_person)
                WHERE OLD.contact_person IS DISTINCT FROM NEW.contact_person
                UNION ALL
                SELECT 'end_user_name', to_jsonb(OLD.end_user_name), to_jsonb(NEW.end_user_name)
                WHERE OLD.end_user_name IS DISTINCT FROM NEW.end_user_name
                UNION ALL
                SELECT 'stove_serial_no', to_jsonb(OLD.stove_serial_no), to_jsonb(NEW.stove_serial_no)
                WHERE OLD.stove_serial_no IS DISTINCT FROM NEW.stove_serial_no
                UNION ALL
                SELECT 'assigned_to', to_jsonb(OLD.assigned_to), to_jsonb(NEW.assigned_to)
                WHERE OLD.assigned_to IS DISTINCT FROM NEW.assigned_to
                UNION ALL
                SELECT 'location', to_jsonb(OLD.location), to_jsonb(NEW.location)
                WHERE OLD.location IS DISTINCT FROM NEW.location
                UNION ALL
                SELECT 'notes', to_jsonb(OLD.notes), to_jsonb(NEW.notes)
                WHERE OLD.notes IS DISTINCT FROM NEW.notes
            ) field_comparisons
            WHERE field_name IS NOT NULL
        ) changes_summary;
        
        IF field_changes = '{}'::jsonb THEN
            RETURN NEW;
        END IF;
        
    ELSIF TG_OP = 'DELETE' THEN
        action_type := 'deleted';
        action_description := 'Sale deleted: ' || OLD.transaction_id;
        field_changes := jsonb_build_object(
            'deleted_values', row_to_json(OLD)::jsonb - 'signature'
        );
    END IF;

    SELECT jsonb_build_object(
        'user_agent', current_setting('request.headers', true)::json->>'user-agent',
        'ip_address', current_setting('request.headers', true)::json->>'x-forwarded-for'
    ) INTO user_context;

    INSERT INTO sales_history (
        sale_id,
        action_type,
        action_description,
        field_changes,
        performed_by,
        performed_at,
        ip_address,
        user_agent
    ) VALUES (
        COALESCE(NEW.id, OLD.id),
        action_type,
        action_description,
        field_changes,
        user_id,
        NOW(),
        (user_context->>'ip_address')::INET,
        user_context->>'user_agent'
    );

    RETURN COALESCE(NEW, OLD);
EXCEPTION
    WHEN OTHERS THEN
        RAISE WARNING 'Failed to create sales history: %', SQLERRM;
        RETURN COALESCE(NEW, OLD);
END;
$function$
;
CREATE OR REPLACE FUNCTION public.generate_external_app_token(app_name character varying, app_description text DEFAULT NULL::text, allowed_urls text[] DEFAULT NULL::text[])
 RETURNS TABLE(token character varying, secret_key character varying, application_name character varying)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    new_token character varying;
    new_secret character varying;
BEGIN
    -- Generate random token and secret
    new_token := 'ext_' || encode(gen_random_bytes(16), 'hex');
    new_secret := 'secret_' || encode(gen_random_bytes(20), 'hex');
    
    -- Insert new token
    INSERT INTO external_app_tokens (
        token,
        secret_key,
        application_name,
        application_description,
        allowed_urls,
        is_active,
        usage_count
    ) VALUES (
        new_token,
        new_secret,
        app_name,
        app_description,
        allowed_urls,
        true,
        0
    );
    
    -- Return the generated credentials
    RETURN QUERY
    SELECT new_token, new_secret, app_name;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.get_organization_stove_counts(org_ids uuid[])
 RETURNS TABLE(organization_id uuid, total_count bigint, sold_count bigint, available_count bigint)
 LANGUAGE plpgsql
 STABLE
AS $function$
BEGIN
  RETURN QUERY
  SELECT 
    s.organization_id,
    COUNT(*) as total_count,
    COUNT(*) FILTER (WHERE s.status = 'sold') as sold_count,
    COUNT(*) FILTER (WHERE s.status = 'available') as available_count
  FROM stove_ids s
  WHERE s.organization_id = ANY(org_ids)
  GROUP BY s.organization_id;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.get_sales_history(p_organization_id uuid, p_user_id uuid DEFAULT NULL::uuid, p_limit integer DEFAULT 50, p_offset integer DEFAULT 0, p_action_type character varying DEFAULT NULL::character varying, p_start_date timestamp without time zone DEFAULT NULL::timestamp without time zone, p_end_date timestamp without time zone DEFAULT NULL::timestamp without time zone)
 RETURNS TABLE(id uuid, sale_id uuid, action_type character varying, action_description text, field_changes jsonb, performed_by uuid, performed_at timestamp with time zone, transaction_id character varying, sale_amount numeric, sale_status character varying, performer_name text, performer_email text)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    RETURN QUERY
    SELECT 
        sh.id,
        sh.sale_id,
        sh.action_type,
        sh.action_description,
        sh.field_changes,
        sh.performed_by,
        sh.performed_at,
        s.transaction_id,
        s.amount as sale_amount,
        s.status as sale_status,
        p.full_name as performer_name,
        p.email as performer_email
    FROM sales_history sh
    JOIN sales s ON s.id = sh.sale_id
    JOIN profiles p ON p.id = sh.performed_by
    WHERE s.organization_id = p_organization_id
        AND (p_user_id IS NULL OR sh.performed_by = p_user_id)
        AND (p_action_type IS NULL OR sh.action_type = p_action_type)
        AND (p_start_date IS NULL OR sh.performed_at >= p_start_date)
        AND (p_end_date IS NULL OR sh.performed_at <= p_end_date)
    ORDER BY sh.performed_at DESC
    LIMIT p_limit OFFSET p_offset;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.get_table_count(table_name text)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    result integer;
BEGIN
    -- Execute dynamic SQL to count records
    EXECUTE format('SELECT count(*) FROM %I', table_name) INTO result;
    RETURN result;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  user_role text := new.raw_user_meta_data->>'role';
  org_id uuid := nullif(new.raw_user_meta_data->>'organization_id', '')::uuid;
begin
  insert into public.profiles (
    id,
    email,
    full_name,
    role,
    organization_id,
    has_changed_password
  )
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    user_role,
    org_id,
    case
      when user_role = 'admin' then true
      else false
    end
  );
  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.handle_user_delete()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  delete from public.profiles where id = old.id;
  return old;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.handle_user_deletion()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  delete from public.profiles where id = old.id;
  return old;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.handle_user_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  update public.profiles
  set full_name = new.raw_user_meta_data->>'full_name'
  where id = new.id;
  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = _user_id
      AND role = _role
  );
$function$
;
CREATE OR REPLACE FUNCTION public.list_external_app_tokens()
 RETURNS TABLE(token character varying, application_name character varying, application_description text, allowed_urls text[], usage_count integer, last_used_at timestamp with time zone, created_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    RETURN QUERY
    SELECT 
        t.token,
        t.application_name,
        t.application_description,
        t.allowed_urls,
        t.usage_count,
        t.last_used_at,
        t.created_at
    FROM external_app_tokens t
    WHERE t.is_active = true
    ORDER BY t.created_at DESC;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.manual_create_sales_history(p_sale_id uuid, p_action_type character varying, p_action_description text, p_field_changes jsonb DEFAULT NULL::jsonb, p_performed_by uuid DEFAULT NULL::uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    history_id UUID;
    user_id UUID;
BEGIN
    -- Use provided user or current auth user
    user_id := COALESCE(p_performed_by, auth.uid());
    
    -- If still no user, try custom setting
    IF user_id IS NULL THEN
        user_id := current_setting('app.current_user_id', true)::UUID;
    END IF;
    
    IF user_id IS NULL THEN
        RAISE EXCEPTION 'No user context available for history creation';
    END IF;

    -- Insert history record
    INSERT INTO sales_history (
        sale_id,
        action_type,
        action_description,
        field_changes,
        performed_by,
        performed_at
    ) VALUES (
        p_sale_id,
        p_action_type,
        p_action_description,
        COALESCE(p_field_changes, '{}'::jsonb),
        user_id,
        NOW()
    ) RETURNING id INTO history_id;

    RETURN history_id;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.map_legacy_roles()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.role = 'super_admin_agent' THEN NEW.role := 'acsl_agent'; END IF;
  IF NEW.role = 'admin' THEN NEW.role := 'partner'; END IF;
  IF NEW.role = 'agent' THEN NEW.role := 'partner_agent'; END IF;
  RETURN NEW;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.my_org_id()
 RETURNS uuid
 LANGUAGE sql
 STABLE
AS $function$
  select organization_id from public.profiles where id = auth.uid()
$function$
;
CREATE OR REPLACE FUNCTION public.revoke_external_app_token(token_to_revoke text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    UPDATE external_app_tokens 
    SET is_active = false
    WHERE token = token_to_revoke;
    
    RETURN FOUND;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.sync_last_login()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  -- Only act when last_sign_in_at actually changes
  IF NEW.last_sign_in_at IS DISTINCT FROM OLD.last_sign_in_at THEN
    UPDATE public.profiles
    SET last_login = NEW.last_sign_in_at
    WHERE id = NEW.id;
  END IF;
  RETURN NEW;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.sync_transfer_sales_date_from_history()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.sales_date IS NOT NULL THEN
    UPDATE stove_ids
       SET transfer_sales_date = NEW.sales_date
     WHERE sales_reference = NEW.transaction_id
       AND transfer_sales_date IS DISTINCT FROM NEW.sales_date;
  END IF;
  RETURN NEW;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.sync_transfer_sales_date_on_stove()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.sales_reference IS NOT NULL AND NEW.transfer_sales_date IS NULL THEN
    SELECT max(sales_date) INTO NEW.transfer_sales_date
    FROM stove_transfer_history
    WHERE transaction_id = NEW.sales_reference
      AND sales_date IS NOT NULL;
  END IF;
  RETURN NEW;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.sync_user_role_to_auth()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    -- Update the auth.users raw_user_meta_data with the role from profiles
    UPDATE auth.users 
    SET raw_user_meta_data = COALESCE(raw_user_meta_data, '{}'::jsonb) || jsonb_build_object('role', NEW.role)
    WHERE id = NEW.id;
    
    RETURN NEW;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.update_credentials_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.update_payment_models_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.update_sale_status()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Automatically calculate and update status
  NEW.status = public.calculate_sale_status(NEW);
  RETURN NEW;
END;
$function$
;
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$
;

-- ============ triggers ============
CREATE TRIGGER sales_history_trigger AFTER INSERT OR DELETE OR UPDATE ON public.sales FOR EACH ROW EXECUTE FUNCTION create_sales_history();
CREATE TRIGGER sales_status_calculation_insert BEFORE INSERT ON public.sales FOR EACH ROW EXECUTE FUNCTION calculate_sale_status();
CREATE TRIGGER sales_status_calculation_update BEFORE UPDATE ON public.sales FOR EACH ROW EXECUTE FUNCTION calculate_sale_status();
CREATE TRIGGER sync_profile_role_trigger AFTER INSERT OR UPDATE OF role ON public.profiles FOR EACH ROW EXECUTE FUNCTION sync_user_role_to_auth();
CREATE TRIGGER trg_history_transfer_sales_date AFTER INSERT OR UPDATE OF sales_date ON public.stove_transfer_history FOR EACH ROW EXECUTE FUNCTION sync_transfer_sales_date_from_history();
CREATE TRIGGER trg_map_legacy_roles_credentials BEFORE INSERT OR UPDATE ON public.credentials FOR EACH ROW EXECUTE FUNCTION map_legacy_roles();
CREATE TRIGGER trg_map_legacy_roles_profiles BEFORE INSERT OR UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION map_legacy_roles();
CREATE TRIGGER trg_stove_transfer_sales_date BEFORE INSERT OR UPDATE OF sales_reference ON public.stove_ids_base FOR EACH ROW EXECUTE FUNCTION sync_transfer_sales_date_on_stove();
CREATE TRIGGER trigger_update_credentials_updated_at BEFORE UPDATE ON public.credentials FOR EACH ROW EXECUTE FUNCTION update_credentials_updated_at();
CREATE TRIGGER trigger_update_payment_models_updated_at BEFORE UPDATE ON public.payment_models FOR EACH ROW EXECUTE FUNCTION update_payment_models_updated_at();
CREATE TRIGGER trigger_update_sale_status BEFORE INSERT OR UPDATE ON public.sales FOR EACH ROW EXECUTE FUNCTION update_sale_status();
CREATE TRIGGER update_organizations_updated_at BEFORE UPDATE ON public.organizations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============ row level security ============
alter table public."acsl_agent_organizations" enable row level security;
alter table public."acsl_agent_states" enable row level security;
alter table public."addresses" enable row level security;
alter table public."app_releases" enable row level security;
alter table public."app_settings" enable row level security;
alter table public."cancelled_purchases" enable row level security;
alter table public."credentials" enable row level security;
alter table public."email_config" enable row level security;
alter table public."email_logs" enable row level security;
alter table public."external_app_tokens" enable row level security;
alter table public."installment_payments" enable row level security;
alter table public."nigeria_lgas" enable row level security;
alter table public."nigeria_states" enable row level security;
alter table public."organization_payment_models" enable row level security;
alter table public."organizations" enable row level security;
alter table public."organizations_backup_20251002" enable row level security;
alter table public."payment_models" enable row level security;
alter table public."profiles" enable row level security;
alter table public."sales" enable row level security;
alter table public."sales_history" enable row level security;
alter table public."sales_images" enable row level security;
alter table public."stove_ids_base" enable row level security;
alter table public."stove_transfer_history" enable row level security;
alter table public."sync_logs" enable row level security;
alter table public."uploads" enable row level security;

-- ============ policies ============
create policy "agent_read_own" on public."acsl_agent_organizations" as permissive for select to "authenticated"
  using ((agent_id = auth.uid()));
create policy "super_admin_full_access" on public."acsl_agent_organizations" as permissive for all to "authenticated"
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))));
create policy "agent_read_own" on public."acsl_agent_states" as permissive for select to "authenticated"
  using ((agent_id = auth.uid()));
create policy "super_admin_full_access" on public."acsl_agent_states" as permissive for all to "authenticated"
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))));
create policy "authenticated_users_insert_addresses" on public."addresses" as permissive for insert to "authenticated"
  with check (true);
create policy "authenticated_users_read_addresses" on public."addresses" as permissive for select to "authenticated"
  using (true);
create policy "service_role_access" on public."addresses" as permissive for all to "service_role"
  using (true)
  with check (true);
create policy "super_admin_addresses_access" on public."addresses" as permissive for all to "authenticated"
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))))
  with check ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))));
create policy "Public can read app release" on public."app_releases" as permissive for select to "public"
  using (true);
create policy "service_role_read" on public."app_settings" as permissive for select to "public"
  using ((auth.role() = 'service_role'::text));
create policy "super_admin_full_access" on public."app_settings" as permissive for all to "public"
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))));
create policy "super_admin_insert_cancelled_purchases" on public."cancelled_purchases" as permissive for insert to "authenticated"
  with check ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND (p.role = 'super_admin'::text)))));
create policy "super_admin_select_cancelled_purchases" on public."cancelled_purchases" as permissive for select to "authenticated"
  using ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND (p.role = 'super_admin'::text)))));
create policy "Admins can view all credentials" on public."credentials" as permissive for select to "authenticated"
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['admin'::text, 'super_admin'::text]))))));
create policy "Service role can insert credentials" on public."credentials" as permissive for insert to "service_role"
  with check (true);
create policy "Service role can update credentials" on public."credentials" as permissive for update to "service_role"
  using (true);
create policy "Super admins can delete credentials" on public."credentials" as permissive for delete to "authenticated"
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))));
create policy "Service role full access" on public."email_config" as permissive for all to "public"
  using (true);
create policy "Service role full access" on public."email_logs" as permissive for all to "public"
  using (true);
create policy "org_members_insert_own_sales" on public."installment_payments" as permissive for insert to "public"
  with check ((sale_id IN ( SELECT s.id
   FROM sales s
  WHERE (s.organization_id IN ( SELECT profiles.organization_id
           FROM profiles
          WHERE (profiles.id = auth.uid()))))));
create policy "org_members_read_own_sales" on public."installment_payments" as permissive for select to "public"
  using ((sale_id IN ( SELECT s.id
   FROM sales s
  WHERE (s.organization_id IN ( SELECT profiles.organization_id
           FROM profiles
          WHERE (profiles.id = auth.uid()))))));
create policy "service_role_access" on public."installment_payments" as permissive for all to "public"
  using (true)
  with check (true);
create policy "super_admin_full_access" on public."installment_payments" as permissive for all to "public"
  using (true)
  with check (true);
create policy "nigeria_lgas_read" on public."nigeria_lgas" as permissive for select to "authenticated"
  using (true);
create policy "nigeria_states_read" on public."nigeria_states" as permissive for select to "authenticated"
  using (true);
create policy "org_members_read_own" on public."organization_payment_models" as permissive for select to "public"
  using ((organization_id IN ( SELECT profiles.organization_id
   FROM profiles
  WHERE (profiles.id = auth.uid()))));
create policy "super_admin_full_access" on public."organization_payment_models" as permissive for all to "public"
  using (true)
  with check (true);
create policy "admin_organization_management" on public."organizations" as permissive for all to "authenticated"
  using ((id IN ( SELECT profiles.organization_id
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))))
  with check ((id IN ( SELECT profiles.organization_id
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));
create policy "service_role_access" on public."organizations" as permissive for all to "service_role"
  using (true)
  with check (true);
create policy "super_admin_organizations_access" on public."organizations" as permissive for all to "authenticated"
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))))
  with check ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))));
create policy "users_organization_access" on public."organizations" as permissive for select to "authenticated"
  using ((id IN ( SELECT profiles.organization_id
   FROM profiles
  WHERE (profiles.id = auth.uid()))));
create policy "authenticated_read_active" on public."payment_models" as permissive for select to "public"
  using ((is_active = true));
create policy "super_admin_full_access" on public."payment_models" as permissive for all to "public"
  using (true)
  with check (true);
create policy "Super admins can update any profile" on public."profiles" as permissive for update to "authenticated"
  using (has_role(auth.uid(), 'super_admin'::text))
  with check (has_role(auth.uid(), 'super_admin'::text));
create policy "allow_profile_creation" on public."profiles" as permissive for insert to "authenticated"
  with check ((id = auth.uid()));
create policy "service_role_access" on public."profiles" as permissive for all to "service_role"
  using (true)
  with check (true);
create policy "users_read_own_profile" on public."profiles" as permissive for select to "authenticated"
  using ((id = auth.uid()));
create policy "users_update_own_profile" on public."profiles" as permissive for update to "authenticated"
  using ((id = auth.uid()))
  with check ((id = auth.uid()));
create policy "admin_org_sales_management" on public."sales" as permissive for all to "authenticated"
  using ((organization_id IN ( SELECT profiles.organization_id
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['admin'::text, 'super_admin'::text]))))))
  with check ((organization_id IN ( SELECT profiles.organization_id
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['admin'::text, 'super_admin'::text]))))));
create policy "service_role_access" on public."sales" as permissive for all to "service_role"
  using (true)
  with check (true);
create policy "super_admin_sales_access" on public."sales" as permissive for all to "authenticated"
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))))
  with check ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))));
create policy "users_org_sales" on public."sales" as permissive for select to "authenticated"
  using ((organization_id IN ( SELECT profiles.organization_id
   FROM profiles
  WHERE (profiles.id = auth.uid())
 LIMIT 1)));
create policy "users_own_sales" on public."sales" as permissive for all to "authenticated"
  using ((created_by = auth.uid()))
  with check ((created_by = auth.uid()));
create policy "System can insert history" on public."sales_history" as permissive for insert to "public"
  with check (true);
create policy "Users can view their own history" on public."sales_history" as permissive for select to "public"
  using (((performed_by = auth.uid()) OR (EXISTS ( SELECT 1
   FROM sales s
  WHERE ((s.id = sales_history.sale_id) AND (s.organization_id IN ( SELECT profiles.organization_id
           FROM profiles
          WHERE (profiles.id = auth.uid()))))))));
create policy "service_role_access" on public."sales_history" as permissive for all to "service_role"
  using (true)
  with check (true);
create policy "Allow organization members to insert stove_ids" on public."stove_ids_base" as permissive for insert to "authenticated"
  with check ((organization_id = auth.uid()));
create policy "Authenticated and service role can select stove_ids" on public."stove_ids_base" as permissive for select to "authenticated", "service_role"
  using (true);
create policy "Authenticated and service role can update stove_ids" on public."stove_ids_base" as permissive for update to "authenticated", "service_role"
  using (true);
create policy "service_role_access" on public."stove_transfer_history" as permissive for all to "service_role"
  using (true)
  with check (true);
create policy "super_admin_full_access" on public."stove_transfer_history" as permissive for all to "authenticated"
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))))
  with check ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))));
create policy "Service role full access" on public."sync_logs" as permissive for all to "public"
  using ((auth.role() = 'service_role'::text));
create policy "Super admins can read sync_logs" on public."sync_logs" as permissive for select to "public"
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['super_admin'::text, 'admin'::text]))))));
create policy "service_role_access" on public."uploads" as permissive for all to "service_role"
  using (true)
  with check (true);
create policy "super_admin_uploads_access" on public."uploads" as permissive for all to "authenticated"
  using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))))
  with check ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'super_admin'::text)))));
create policy "users_own_uploads" on public."uploads" as permissive for all to "authenticated"
  using ((created_by = auth.uid()))
  with check ((created_by = auth.uid()));

-- ============ grants ============
grant delete, insert, references, select, trigger, truncate, update on public."acsl_agent_organizations" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."acsl_agent_organizations" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."acsl_agent_organizations" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."acsl_agent_states" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."acsl_agent_states" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."acsl_agent_states" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."addresses" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."addresses" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."addresses" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."app_releases" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."app_releases" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."app_releases" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."app_settings" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."app_settings" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."app_settings" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."cancelled_purchases" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."cancelled_purchases" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."cancelled_purchases" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."credentials" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."credentials" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."credentials" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."email_config" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."email_config" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."email_config" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."email_logs" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."email_logs" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."email_logs" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."external_app_tokens" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."external_app_tokens" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."external_app_tokens" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."installment_payments" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."installment_payments" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."installment_payments" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."nigeria_lgas" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."nigeria_lgas" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."nigeria_lgas" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."nigeria_states" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."nigeria_states" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."nigeria_states" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."organization_payment_models" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."organization_payment_models" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."organization_payment_models" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."organizations" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."organizations" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."organizations" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."organizations_backup_20251002" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."organizations_backup_20251002" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."organizations_backup_20251002" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."payment_models" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."payment_models" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."payment_models" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."profiles" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."profiles" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."profiles" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."sales" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."sales" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."sales" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."sales_history" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."sales_history" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."sales_history" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."sales_images" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."sales_images" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."sales_images" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."stove_ids" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."stove_ids" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."stove_ids" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."stove_ids_base" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."stove_ids_base" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."stove_ids_base" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."stove_transfer_history" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."stove_transfer_history" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."stove_transfer_history" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."super_admin_agent_organizations" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."super_admin_agent_organizations" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."super_admin_agent_organizations" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."super_admin_agent_states" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."super_admin_agent_states" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."super_admin_agent_states" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."sync_logs" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."sync_logs" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."sync_logs" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."uploads" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."uploads" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."uploads" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."user_org_context" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."user_org_context" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."user_org_context" to "service_role";
grant delete, insert, references, select, trigger, truncate, update on public."user_roles" to "anon";
grant delete, insert, references, select, trigger, truncate, update on public."user_roles" to "authenticated";
grant delete, insert, references, select, trigger, truncate, update on public."user_roles" to "service_role";


-- Supplemental baseline: SALES (oeiwnpngbnkhcismhpgs)
-- Objects NOT covered by the public-schema baseline. Captured 2026-08-14, read-only.

-- ============ auth trigger functions ============
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  user_role text := new.raw_user_meta_data->>'role';
  org_id uuid := nullif(new.raw_user_meta_data->>'organization_id', '')::uuid;
begin
  insert into public.profiles (
    id,
    email,
    full_name,
    role,
    organization_id,
    has_changed_password
  )
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    user_role,
    org_id,
    case
      when user_role = 'admin' then true
      else false
    end
  );
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_user_deletion()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  delete from public.profiles where id = old.id;
  return old;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_user_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  update public.profiles
  set full_name = new.raw_user_meta_data->>'full_name'
  where id = new.id;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.sync_last_login()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  -- Only act when last_sign_in_at actually changes
  IF NEW.last_sign_in_at IS DISTINCT FROM OLD.last_sign_in_at THEN
    UPDATE public.profiles
    SET last_login = NEW.last_sign_in_at
    WHERE id = NEW.id;
  END IF;
  RETURN NEW;
END;
$function$
;

-- ============ auth.users triggers ============
-- Without these, signup on a fresh environment creates an auth user with no
-- profile row, and permission checks resolve to null.
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
CREATE TRIGGER on_auth_user_deleted AFTER DELETE ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_user_deletion();
CREATE TRIGGER on_auth_user_login AFTER UPDATE OF last_sign_in_at ON auth.users FOR EACH ROW EXECUTE FUNCTION sync_last_login();
CREATE TRIGGER on_auth_user_updated AFTER UPDATE ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_user_update();

-- ============ storage buckets (DATA, not DDL) ============
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  values ('images', 'images', true, null, null)
  on conflict (id) do nothing;

-- ============ storage policies ============
create policy "Allow authenticated inserts to images" on storage."objects" as permissive for insert to "authenticated"
  with check ((bucket_id = 'images'::text));
create policy "Allow authenticated select from images" on storage."objects" as permissive for select to "authenticated"
  using ((bucket_id = 'images'::text));
create policy "Allow authenticated updates to images" on storage."objects" as permissive for update to "authenticated"
  using ((bucket_id = 'images'::text))
  with check ((bucket_id = 'images'::text));

-- ============ realtime publication ============
-- (none)

-- ============ cron jobs — DOCUMENTATION ONLY ============
-- !! DELIBERATELY NOT EXECUTABLE. These are commented out on purpose.
-- Any non-production environment that inherits these will run them against
-- real integrations. The ERP's low-stock job sends EMAIL to real recipients.
-- job: refresh-geo-data-weekly   schedule: 0 2 * * 0
--   
--         select net.http_post(
--           url     := (select decrypted_secret from vault.decrypted_secrets where name = 'project_url')
--                      || '/functions/v1/refresh-geo-data',
--           headers := jsonb_build_object(
--             'Content-Type', 'application/json',
--             'Authorization', 'Bearer ' || (select decrypted_secret from vault.decrypted_secrets where name = 'service_role_key')
--           ),
--           body    := '{}'::jsonb
--         );
--         
